# Generated by Django 5.0.6 on 2024-08-28 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlicenseapplication',
            name='NIN',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='NIN must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
